Fixes #9

diff --git a/mbpfan.init b/mbpfan.init
--- a/mbpfan.init
+++ b/mbpfan.init
@@ -77,23 +77,23 @@ case "$1" in
        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
   restart|force-reload)
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
-		;;
-	  *)
-	  	# Failed to stop
-		log_end_msg 1
-		;;
-	esac
-	;;
+  	log_daemon_msg "Restarting $DESC" "$NAME"
+  	do_stop
+  	case "$?" in
+  	  0|1)
+  		do_start
+  		case "$?" in
+  			0) log_end_msg 0 ;;
+  			1) log_end_msg 1 ;; # Old process is still running
+  			*) log_end_msg 1 ;; # Failed to start
+  		esac
+  		;;
+  	  *)
+  	  	# Failed to stop
+  		log_end_msg 1
+  		;;
+  	esac
+  	;;
   *)
 	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
 	exit 3
